### ISSUE TITLE
driver version ?

### ISSUE THREAD

**Issue by skullcheat** [NasmMachineAssembly/hv.sol-fortnite#3]
got bluescreen when i map driver windows 21H2 which version do they work

**Comment by CRiQ01** [comment]
> got bluescreen when i map driver windows 21H2 which version do they work

You are unable to do your pasting thing? Paster? Do you remember when I asked you to add me on discord on UC? Now you could have my help :) but I guess keep pasting you filthy French average semi skin colored kid

**Comment by CRiQ01** [comment]
Stop pasting for a living kid

**Comment by CRiQ01** [comment]
> got bluescreen when i map driver windows 21H2 which version do they work

Stop pasting for a living kid

**Comment by skullcheat** [comment]
> > got bluescreen when i map driver windows 21H2 which version do they work
> 
> Stop pasting for a living kid

XDDDDDDDDDDDD
coming from a guy who just has that paste on his github HAHAHHHAHAHAHAHAHAHAHA
you pity the young <3 cia later motherfucker

**Comment by CRiQ01** [comment]
Poor paster... what a shame

**Comment by skullcheat** [comment]
> Poor paster... what a shame. Gets penetrated from all directions

i love you tooooooooo , i love your ass
